shell: zsh
_42:
  active: false
  recovery: false
  user: abarthel
  email: abarthel@student.42.fr
git:
  active: true
  name: Antoine Barthelemy
  email: abarthel@student.42.fr
kubernetes:
  active: true
  autocompletion: true
  alias: true
vim:
  active: true
  replace: false
zsh_powerlevel10k:
  active: true
  replace: false
